server:
    compression:
        enabled: true
        excluded-user-agents: text/html,text/xml,text/plain,text/css
        mime-types: application/json,application/xml,
        min-response-size: 256
