server:
    tomcat:
        accesslog:
            directory: web-access
            enabled: true
            pattern: combined
            prefix: ebank-access
            suffix: .log
        basedir: D:\temp
